-- execute these in flink sql-client

INSERT INTO TEST_BAD 
SELECT 
    ID,
    NAME,
    LOCALTIMESTAMP as W_INSERT_DT,
    CAST(ID AS STRING) AS INTEGRATION_ID
FROM TEST;


INSERT INTO TEST_GOOD 
SELECT 
    ID,
    NAME,
    CAST(ID AS STRING) AS INTEGRATION_ID
FROM TEST;